[project]
name = 'symmetrical'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []
[contracts.emergency_pause]
path = 'contracts/emergency_pause.clar'
clarity_version = 2
epoch = 2.5

[contracts.governance]
path = 'contracts/governance.clar'
clarity_version = 2
epoch = 2.5

[contracts.multi_send_with_retry_logic]
path = 'contracts/multi_send_with_retry_logic.clar'
clarity_version = 2
epoch = 2.5

[contracts.storage_with_access_logs]
path = 'contracts/storage_with_access_logs.clar'
clarity_version = 2
epoch = 2.5

[contracts.store_with_confirmation_steps]
path = 'contracts/store_with_confirmation_steps.clar'
clarity_version = 2
epoch = 2.5

[contracts.two_factor_withdrawal_wallet]
path = 'contracts/two_factor_withdrawal_wallet.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
